using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;

namespace ReverbandAmbianceOverhaulPatcher
{
    public class Program
    {
        private static readonly RegionSounds.TranslationMask SoundChancesOnlyMask = new(defaultOn: false)
        {
            Sounds = true,
        };

        private static Lazy<Settings> _settings = null!;
        private static Settings Settings => _settings.Value;

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddRunnabilityCheck(CheckRunnability)
                .SetAutogeneratedSettings("Settings", "settings.json", out _settings)
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetTypicalOpen(GameRelease.SkyrimSE, "SynthesisReverbAndAmbianceOverhaulPatch.esp")
                .Run(args);
        }

        public static void CheckRunnability(IRunnabilityState state)
        {
            var sourceModKey = GetSourceModKey();
            if (!state.LoadOrder.ContainsKey(sourceModKey))
            {
                throw new ArgumentException($"{sourceModKey.FileName} is required in the load order.");
            }
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            var sourceModKey = GetSourceModKey();
            var listing = state.LoadOrder.ListedOrder.FirstOrDefault(x => x.ModKey == sourceModKey);
            if (listing?.Mod is not { } sourceMod)
            {
                throw new ArgumentException($"Unable to load {sourceModKey.FileName}.");
            }

            ForwardAcousticSpaces(state, sourceMod, sourceModKey);
            ForwardRegionSoundChances(state, sourceMod, sourceModKey);
        }

        private static void ForwardAcousticSpaces(
            IPatcherState<ISkyrimMod, ISkyrimModGetter> state,
            ISkyrimModGetter sourceMod,
            ModKey sourceModKey)
        {
            var patched = 0;
            foreach (var sourceCell in sourceMod.EnumerateMajorRecords<ICellGetter>())
            {
                if (sourceCell.IsDeleted)
                {
                    continue;
                }

                if (!state.LinkCache.TryResolveContext<ICell, ICellGetter>(sourceCell.FormKey, out var winningContext))
                {
                    Console.WriteLine($"Skipping {CellLabel(sourceCell)}: winning override could not be resolved.");
                    continue;
                }

                if (winningContext.ModKey == sourceModKey)
                {
                    continue;
                }

                var winningCell = winningContext.Record;
                if (sourceCell.AcousticSpace.Equals(winningCell.AcousticSpace))
                {
                    continue;
                }

                var patchCell = winningContext.GetOrAddAsOverride(state.PatchMod);
                patchCell.AcousticSpace.SetTo(sourceCell.AcousticSpace);
                patched++;
                Console.WriteLine($"Forwarded XCAS Acoustic Space on {CellLabel(sourceCell)} from {winningContext.ModKey.FileName}.");
            }

            Console.WriteLine($"Forwarded CELL XCAS Acoustic Space on {patched} cell(s) from {sourceModKey.FileName}.");
        }

        private static void ForwardRegionSoundChances(
            IPatcherState<ISkyrimMod, ISkyrimModGetter> state,
            ISkyrimModGetter sourceMod,
            ModKey sourceModKey)
        {
            var patched = 0;
            foreach (var sourceRegion in sourceMod.EnumerateMajorRecords<IRegionGetter>())
            {
                if (sourceRegion.IsDeleted)
                {
                    continue;
                }

                if (sourceRegion.Sounds is null)
                {
                    continue;
                }

                if (!state.LinkCache.TryResolveContext<IRegion, IRegionGetter>(sourceRegion.FormKey, out var winningContext))
                {
                    Console.WriteLine($"Skipping {RegionLabel(sourceRegion)}: winning override could not be resolved.");
                    continue;
                }

                if (winningContext.ModKey == sourceModKey)
                {
                    continue;
                }

                if (SoundChancesEqual(sourceRegion.Sounds, winningContext.Record.Sounds))
                {
                    continue;
                }

                var patchRegion = winningContext.GetOrAddAsOverride(state.PatchMod);
                ForwardSoundChances(patchRegion, sourceRegion.Sounds);
                patched++;
                Console.WriteLine($"Forwarded Region Sound Chances on {RegionLabel(sourceRegion)} from {winningContext.ModKey.FileName}.");
            }

            Console.WriteLine($"Forwarded Region Sound Chances on {patched} region(s) from {sourceModKey.FileName}.");
        }

        private static void ForwardSoundChances(IRegion patchRegion, IRegionSoundsGetter sourceSounds)
        {
            if (patchRegion.Sounds is null)
            {
                patchRegion.Sounds = sourceSounds.DeepCopy();
                return;
            }

            patchRegion.Sounds.DeepCopyIn(sourceSounds, SoundChancesOnlyMask);
        }

        private static bool SoundChancesEqual(IRegionSoundsGetter? left, IRegionSoundsGetter? right)
        {
            var leftSounds = left?.Sounds;
            var rightSounds = right?.Sounds;
            if (ReferenceEquals(leftSounds, rightSounds))
            {
                return true;
            }

            if (leftSounds is null || rightSounds is null)
            {
                return leftSounds is null && rightSounds is null;
            }

            if (leftSounds.Count != rightSounds.Count)
            {
                return false;
            }

            for (var i = 0; i < leftSounds.Count; i++)
            {
                var leftSound = leftSounds[i];
                var rightSound = rightSounds[i];
                if (!leftSound.Sound.Equals(rightSound.Sound)
                    || leftSound.Flags != rightSound.Flags
                    || !leftSound.Chance.Equals(rightSound.Chance))
                {
                    return false;
                }
            }

            return true;
        }

        private static ModKey GetSourceModKey()
        {
            var name = Settings.SourcePlugin?.Trim() ?? string.Empty;
            if (name.Length == 0)
            {
                throw new ArgumentException("Source Plugin must be set in the patcher settings.");
            }

            try
            {
                return ModKey.FromNameAndExtension(name);
            }
            catch (ArgumentException)
            {
                throw new ArgumentException($"Source Plugin '{name}' is not a valid plugin file name.");
            }
        }

        private static string CellLabel(ICellGetter cell)
        {
            return cell.EditorID ?? cell.FormKey.ToString();
        }

        private static string RegionLabel(IRegionGetter region)
        {
            return region.EditorID ?? region.FormKey.ToString();
        }
    }
}
